---
- name: Initialize Kubernetes master node
  hosts: master
  become: true
  gather_facts: yes
  vars:
    kubeadm_config: /etc/kubernetes/admin.conf

  tasks:
    - name: Initialize cluster
      command: >
        kubeadm init
        --pod-network-cidr=10.244.0.0/16
        --cri-socket {{ cri_socket }}
        --kubernetes-version {{ kubernetes_version }}
      register: init_result
      args:
        creates: "{{ kubeadm_config }}"

    - name: Display kubeadm init output
      debug:
        var: init_result.stdout_lines

    - name: Ensure artifacts directory exists locally
      delegate_to: localhost
      become: false
      file:
        path: "{{ artifacts_dir }}"
        state: directory
        mode: '0755'

    - name: Fetch admin.conf locally
      fetch:
        src: "{{ kubeadm_config }}"
        dest: "{{ artifacts_dir }}/admin.conf"
        flat: yes

    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_cmd

    - name: Write join command locally
      delegate_to: localhost
      become: false
      copy:
        content: "{{ (join_cmd.stdout | trim) }} --cri-socket {{ cri_socket }}\n"
        dest: "{{ artifacts_dir }}/join-command.sh"
        mode: '0755'
