- name: Fetch kubeconfig from master
  hosts: master
  become: true
  gather_facts: false
  tasks:
    - name: Ensure local output dir
      delegate_to: localhost
      become: false
      file:
        path: "{{ playbook_dir }}/../output"
        state: directory
        mode: '0755'

    - name: Fetch admin.conf
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: "{{ playbook_dir }}/../output/admin.conf"
        flat: yes