- name: Join workers to the cluster
  hosts: workers
  become: true
  gather_facts: false
  vars:
    join_script_local: "{{ playbook_dir }}/../output/join-command.sh"
    join_script_remote: /tmp/join-command.sh

  pre_tasks:
    - name: Assert local join script exists
      delegate_to: localhost
      become: false
      stat:
        path: "{{ join_script_local }}"
      register: join_local
    - name: Fail if join script missing
      delegate_to: localhost
      become: false
      fail:
        msg: "join-command.sh introuvable : {{ join_script_local }}. Relance l’init master pour le générer."
      when: not join_local.stat.exists

  tasks:
    - name: Copy join script to worker
      copy:
        src: "{{ join_script_local }}"
        dest: "{{ join_script_remote }}"
        mode: '0755'

    - name: Run join script
      command: "sh {{ join_script_remote }}"
      register: join_out
      changed_when: "'This node has joined' in (join_out.stdout | default('')) or join_out.rc == 0"

    - name: Show join output
      debug:
        var: join_out.stdout_lines